export const workshops = [
    {
        id: 1,
        title: 'Raspberry Pi Workshop',
        organisation: 'SheCodes',
        description:
            'Unlock the potential of the Raspberry Pi in this hands-on workshop designed for beginners and tech enthusiasts alike. Learn how to set up your Raspberry Pi, explore its capabilities, and create exciting projects like home automation, media servers, or basic coding applications. Gain practical skills in hardware setup, Linux commands, and Python programming while diving into the world of affordable computing and innovation. Perfect for anyone eager to tinker, learn, and build!',
        dateCreated: '11/01/2025',
        startDate: '25/02/2025',
        endDate: '25/02/2025',
        image: 'https://www.svgrepo.com/show/508699/landscape-placeholder.svg',
        location: 'Perth',
        createdBy: 'Sarah Parker',
        codingLanguage: 'Python',
        isArchived: false,
        category: '',
    },
    {
        id: 2,
        title: 'Intro to JavaScript',
        organisation: 'KhanAcademy',
        description:
            'Dive into the world of programming with this full-day, hands-on workshop on JavaScript, one of the most widely used languages for web development. Perfect for beginners, this session will cover the fundamentals of JavaScript, including variables, functions, loops, and events. You’ll also explore how JavaScript interacts with HTML and CSS to create dynamic, interactive web pages. By the end of the day, you’ll have built a small project and gained the confidence to start your coding journey!',
        dateCreated: '10/02/2025',
        startDate: '11/01/2025',
        endDate: '10/02/2025',
        image: 'https://www.svgrepo.com/show/508699/landscape-placeholder.svg',
        location: 'Melbourne',
        createdBy: 'Sarah Parker',
        codingLanguage: 'JavaScript',
        isArchived: false,
        category: '',
    },
    {
        id: 3,
        title: 'Python for Everyday Use: Simplifying Daily Tasks',
        organisation: 'CodersDirect',
        description:
            'Discover how Python can streamline your daily tasks and boost productivity. This hands-on workshop will cover practical use cases, including automating repetitive tasks, working with data, managing files, and more. Whether you’re a beginner or looking to sharpen your Python skills, you’ll walk away with practical knowledge to integrate Python into your everyday routine. No prior experience required!',
        dateCreated: '11/01/2025',
        startDate: '05/03/2025',
        endDate: null,
        image: 'https://www.svgrepo.com/show/508699/landscape-placeholder.svg',
        location: 'Canberra',
        createdBy: 'Michael Chen',
        codingLanguage: 'Python',
        isArchived: false,
        category: '',
    },
    {
        id: 4,
        title: 'Mastering TypeScript: Build Scalable Web Applications',
        organisation: 'SheCodes',
        description:
            'Dive into the power of TypeScript and learn how it enhances JavaScript to create scalable and robust web applications. This workshop will guide you through TypeScript basics, type definitions, interfaces, and advanced features like generics. Perfect for developers aiming to write cleaner, more reliable code. No prior experience with TypeScript is necessary, but JavaScript familiarity is recommended.',
        dateCreated: '15/01/2025',
        startDate: '20/03/2025',
        endDate: '20/03/2025',
        image: 'https://www.svgrepo.com/show/508699/landscape-placeholder.svg',
        location: 'Sydney',
        createdBy: 'Michael Chen',
        codingLanguage: 'TypeScript',
        isArchived: false,
        category: '',
    },
    {
        id: 5,
        title: 'SQL Essentials: Managing Databases with Confidence',
        organisation: 'SheCodes',
        description:
            "Uncover the fundamentals of SQL in this practical workshop designed to demystify databases. From writing simple queries to joining tables and optimizing data retrieval, this session is tailored for both beginners and those refreshing their skills. Learn to manage, manipulate, and analyze data like a pro while exploring real-world scenarios. By the end, you'll have a strong foundation to confidently use SQL in any project.",
        dateCreated: '17/01/2025',
        startDate: '25/03/2025',
        endDate: '25/03/2025',
        image: 'https://www.svgrepo.com/show/508699/landscape-placeholder.svg',
        location: 'Hobart',
        createdBy: 'Michael Chen',
        codingLanguage: 'SQL',
        isArchived: false,
        category: '',
    },
];
